esphome:
  name: esp32s3-amr-conveyor
  friendly_name: esp32s3-amr-conveyor

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:
  hardware_uart: uart0

# Enable Home Assistant API
api:
  encryption:
    key: "6R+RJ2nermStOC6VTRhAcKmpVJG9QF/tj2LgcsZdV3s="

ota:
  password: "388119d01aa9e91997fd445dc18c00e8"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32S3-Amr-Conveyor"
    password: "gtruPsV8aPEJ"

  # Optional manual IP
  manual_ip:
    static_ip: 192.168.10.144
    gateway: 192.168.10.1
    subnet: 255.255.255.0

captive_portal:

web_server:
  port: 80

# =========================================
switch:
  # OnBoard LED
  - platform: gpio
    pin: GPIO46
    name: "OnBoard LED"
    id: onboard_led

# =========================================
binary_sensor:
  # OnBoard Button
  - platform: gpio
    pin: 
      number: GPIO0
      inverted: true
    name: "OnBoard Button"
    id: onboard_button
    on_press:
      then:
        - switch.toggle: onboard_led
