esphome:
  name: ${esphome_name}
  friendly_name: ${esphome_name}
  min_version: 2024.9.2

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    version: 5.1.2
    platform_version: platformio/espressif32@6.5.0
  flash_size: 4MB
  variant: ESP32S3

# Enable logging
logger:
  level: DEBUG
  hardware_uart: UART0
  

# Enable Home Assistant API
api:
  encryption:
    key: "a1/hZL6Bzi2NMd8WN8E8A7Ap2ARSctGmMYT3iLquTEE="
  reboot_timeout: 0s

ota:
  - platform: esphome
    password: "ota01234567"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${esphome_name}
    password: "ap01234567"

captive_portal:

web_server:
  version: 3

## ==================================================

